### ISSUE TITLE
Add this Script too

### ISSUE THREAD

**Issue by Fawadkhanfk** [KathanP19/gaussrf#3]
https://gist.github.com/hussein98d/d09b5990ff339dac8029b1e9248d2875

**Comment by KathanP19** [comment]
sure will try to add this

**Comment by KathanP19** [comment]
Done you can use -ap to use this feature.

> For Example

`./ssrf.sh domain.com -ap` 

> Or

`./ssrf.sh domain.com -o output_directory -ap`
